#!/usr/bin/env bash

echo -n 'Starting a Cassandra cluster ...'; 
timeout 60 bash -c 'until cqlsh -e "describe cluster" >/dev/null 2>&1; do sleep 2; echo -n "."; done'; 
echo ' DONE!'
echo "Cassandra successfully started."



      
